#Title          : Balance Scale Weight & Distance Database
Number of Instances: 625 (49 balanced, 288 left, 288 right)
Number of Attributes: 4 (numeric) + class name = 5
Attribute Information:

    Class Name (Target variable): 3
        L [balance scale tip to the left]
        B [balance scale be balanced]
        R [balance scale tip to the right]
    Left-Weight: 5 (1, 2, 3, 4, 5)
    Left-Distance: 5 (1, 2, 3, 4, 5)
    Right-Weight: 5 (1, 2, 3, 4, 5)
    Right-Distance: 5 (1, 2, 3, 4, 5)

    Missing Attribute Values: None
    Class Distribution:
        46.08 percent are L
        07.84 percent are B
        46.08 percent are R

Decision Tree 

1) Using Entropy (Information Gain)

2) Using Gini


In [3]:
#Import Libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix



/home/ashu6811/miniconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [23]:
#Load and prepare data
data = pd.read_csv('balance_scale.csv')
print(data.shape)
print(data.head(10))
var = data.columns.values
for i in var:
    print('Range (unique()) for ',i,' is :',data[i].unique(), ' with counts :', data[i].value_counts())


    

(624, 5)
   B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1
5  R  1    1    2    2
6  R  1    1    2    3
7  R  1    1    2    4
8  R  1    1    2    5
9  R  1    1    3    1
Range (unique()) for  B  is : ['R' 'L' 'B']  with counts : L    288
R    288
B     48
Name: B, dtype: int64
Range (unique()) for  1  is : [1 2 3 4 5]  with counts : 5    125
4    125
3    125
2    125
1    124
Name: 1, dtype: int64
Range (unique()) for  1.1  is : [1 2 3 4 5]  with counts : 5    125
4    125
3    125
2    125
1    124
Name: 1.1, dtype: int64
Range (unique()) for  1.2  is : [1 2 3 4 5]  with counts : 5    125
4    125
3    125
2    125
1    124
Name: 1.2, dtype: int64
Range (unique()) for  1.3  is : [2 3 4 5 1]  with counts : 5    125
4    125
3    125
2    125
1    124
Name: 1.3, dtype: int64


In [65]:
#split data
X = data.values[:,1:5]
y = data.values[:,0]
print(X.shape)
print(y.shape)
x_train, x_test, y_train, y_test =train_test_split(X, y, test_size=0.33, random_state=42)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(624, 4)
(624,)
(418, 4) (418,)
(206, 4) (206,)


In [66]:
#Model Prepare using gini index
model_dt_gini = DecisionTreeClassifier(criterion='gini', random_state=100, max_depth=3, min_samples_leaf=5)
result_dt_gini = model_dt_gini.fit(x_train, y_train)
print(result_dt_gini)

model_dt_entropy = DecisionTreeClassifier(criterion='entropy', random_state=100, max_depth=3, min_samples_leaf=5)
result_dt_entropy = model_dt_entropy.fit(x_train, y_train)
result_dt_entropy

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [67]:
#predict using model
y_pred_gini = model_dt_gini.predict(x_test)
y_pred_entropi = model_dt_entropi.predict(x_test)
print('y predicted using gini index : ',y_pred_gini)
print('\n y is predicted using entropy :', y_pred_entropy) 



 Gini:::::::::

Confusion Matrix:  [[ 0  7  7]
 [ 0 68 27]
 [ 0 17 80]]
y predicted using gini index :  ['L' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'L'
 'R' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R'
 'L' 'L' 'R' 'L' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R'
 'L' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'R' 'L'
 'R' 'R' 'R' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'L'
 'L' 'L' 'L' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'L' 'R'
 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'R' 'R'
 'R' 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'R'
 'R' 'L' 'L' 'R' 'R' 'L' 'R' 'L' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R'
 'R' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L'
 'L' 'L' 'L' 'L' 'R' 'L' 'R' 'R']
Report :               precision    recall  f1-score   su

/home/ashu6811/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [73]:
# accuracy , confusion matrix, recall and precission

print("\n\n Gini:::::::::\n")
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred_gini))
print('\nAccuracy score via Gini Index',accuracy_score(y_test, y_pred_gini)*100)    
print("\nReport : \n", classification_report(y_test, y_pred_gini))

print("\n\n Entropy::::::::\n")
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred_entropy))
print('\nAccuracy score via Entropy :',accuracy_score(y_test, y_pred_entropy)*100)    
print("\nReport : \n", classification_report(y_test, y_pred_entropy))




 Gini:::::::::

Confusion Matrix:  [[ 0  7  7]
 [ 0 68 27]
 [ 0 17 80]]

Accuracy score via Gini Index 71.84466019417476

Report : 
              precision    recall  f1-score   support

          B       0.00      0.00      0.00        14
          L       0.74      0.72      0.73        95
          R       0.70      0.82      0.76        97

avg / total       0.67      0.72      0.69       206



 Entropy::::::::

Confusion Matrix:  [[ 0  7  7]
 [ 0 68 27]
 [ 0 17 80]]

Accuracy score via Entropy : 71.84466019417476

Report : 
              precision    recall  f1-score   support

          B       0.00      0.00      0.00        14
          L       0.74      0.72      0.73        95
          R       0.70      0.82      0.76        97

avg / total       0.67      0.72      0.69       206



/home/ashu6811/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
